name: Send Firebase Notification

on:
  schedule:
    # 8 AM IST = 2:30 AM UTC
    - cron: "30 2 * * *"
    # 2 PM IST = 8:30 AM UTC
    - cron: "30 8 * * *"
    # 8 PM IST = 14:30 UTC
    - cron: "30 14 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Create service-account.json from secret
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json

      - name: Send notification
        run: node index.js
